name: Deploy App
on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to firebase
        run: firebase deploy --token=${{ secrets.FIREBASE_TOKEN }} --project kiphelloworld
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}