name: Deploy App
on:
  push:
    branches:
    - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Ready to deploy
        run: |
          npm install -g firebase-tools
          cd functions
          npm install
      - name: Deploy to Firebase
        run: |
          firebase deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}